# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  NC: '\033[0m'
  PPL: '\033[0;35m'
  AWS_REGION: 'eu-north-1'
  INSTANCE_TYPE: 't3.small'
  PUBLIC_KEY_PATH: '~/.ssh/devbox.pub'

tasks:
  check:
    desc: environment dependency checks
    cmds:
      - |
        if command -v terraform > /dev/null 2>&1; then
          echo -e "{{.GREEN}}terraform find !{{.NC}}"
        else
          echo -e "{{.RED}}terraform not found !{{.NC}}"
          exit 1
        fi
        if command -v aws > /dev/null 2>&1; then
          echo -e "{{.GREEN}}aws find !{{.NC}}"
        else
          echo -e "{{.RED}}aws not found !{{.NC}}"
          exit 1
        fi
        if command -v curl > /dev/null 2>&1; then
          echo -e "{{.GREEN}}curl find !{{.NC}}"
        else
          echo -e "{{.RED}}curl not found !{{.NC}}"
          exit 1
        fi
        if command -v ssh-keygen > /dev/null 2>&1; then
          echo -e "{{.GREEN}}ssh-keygen find !{{.NC}}"
        else
          echo -e "{{.RED}}ssh-keygen not found !{{.NC}}"
          exit 1
        fi
    silent: true

  keygen:
    desc: generate ssh for devbox
    cmds:
      - |
        if [ -f ~/.ssh/devbox ]; then
          echo -e "{{.PPL}}~/.ssh/devbox find !{{.NC}}"
        else
          echo -e "{{.GREEN}}Create ~/.ssh/devbox...{{.NC}}"
          ssh-keygen -t ed25519 -C "devbox" -f ~/.ssh/devbox -N ""
        fi
    silent: true


  up:
    desc: launch devbox
    cmds:
      - task: check
      - task: tfvars
      - |
        if [ ! -d src/.terraform ]; then
          cd src && terraform init
        fi
      - |
        cd src && terraform apply
    silent: true

  down:
    desc: destroy devbox
    cmds:
      - |
        cd src && terraform destroy
    silent: true

  ssh:
    desc: connect to the instance
    cmds:
      - |
        $(cd src && terraform output -raw ssh_command)
    silent: false

  tfvars:
    desc: create terraform.tfvars
    cmds:
      - |
        if [ ! -f ~/.ssh/devbox ]; then
          task keygen
        fi
      - |
        IP_HOST=$(curl -s ifconfig.me)
        if [ -f src/terraform.tfvars ]; then
          source src/terraform.tfvars
        fi
        read -p "AWS region [${aws_region:-eu-north-1}]: " input
        aws_region=${input:-${aws_region:-eu-north-1}}
        read -p "Type of instance [${instance_type:-t3.small}]: " input
        instance_type=${input:-${instance_type:-t3.small}}
        read -p "SSH file path(.pub) [${public_key_path:-~/.ssh/devbox.pub}]: " input
        public_key_path=${input:-${public_key_path:-~/.ssh/devbox.pub}}
        while [ -z "$project_name" ]; do
          read -p $'Project Name [\033[0;31mNO DEFAULT\033[0m]: ' input
          project_name=${input:-${project_name}}
        done
        read -p "Email Github [${git_email:-NO DEFAULT}]: " input
        git_email=${input:-${git_email}}
        while [ -z "$git_email" ]; do
          read -p "Email Github [NO DEFAULT]: " input
          git_email=${input:-${git_email}}
        done
        read -p "Name Github [${git_name:-NO DEFAULT}]: " input
        git_name=${input:-${git_name}}
        while [ -z "$git_name" ]; do
          read -p "Name Github [NO DEFAULT]: " input
          git_name=${input:-${git_name}}
        done
        echo "ip_host=\"${IP_HOST}/32\"" > src/terraform.tfvars
        echo "aws_region=\"${aws_region}\"" >> src/terraform.tfvars
        echo "instance_type=\"${instance_type}\"" >> src/terraform.tfvars
        echo "public_key_path=\"${public_key_path}\"" >> src/terraform.tfvars
        echo "project_name=\"${project_name}\"" >> src/terraform.tfvars
        echo "git_email=\"${git_email}\"" >> src/terraform.tfvars
        echo "git_name=\"${git_name}\"" >> src/terraform.tfvars
    silent: true
